# This docker file you create a ubuntu container that you can connect to via ssh and start CARiSMA from a remote server
#
# 1. Create an authorized_keys file in this directory that contains the public SSH key(s) of user(s) that should be able to login to the container
#
# 2. build image with:
#     `docker build -f Dockerfile-ssh -t carisma .`
#
# 3. run container with (container's port 22 is mapped to docker host's port 3000):
#     `docker run -it -e DISPLAY=$DISPLAY -p 3000:22 --name carisma carisma`
#
# 4. connect via ssh and run CARiSMA:
#     `ssh -X -p 3000 root@<docker-host> /opt/carisma/carisma-launcher`
#
FROM --platform=linux/amd64 ubuntu:24.04

# Run command on the image to install Java, openjdk is required although "shipped with the product" (already checked)
RUN apt-get -y update && \
    apt-get install -y \
    openssh-server \
    openjdk-21-jdk \
    wget \
    libc6 libgtk-3-0 libxss1 libnss3 libxtst6 libxrender1 libxi6 libgl1-mesa-dri
# are the following packages required? they could not be found in ubuntu 24.04: libgl1-mesa-glx gconf2 libasound2 libc6-dev

# Configure SSH
RUN mkdir /var/run/sshd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
RUN sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config
RUN sed -i 's/#X11UseLocalhost yes/X11UseLocalhost no/' /etc/ssh/sshd_config
COPY ./authorized_keys /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys
EXPOSE 22

# clean up
RUN apt-get clean

# install carisma
COPY deployment/carisma.product/target/products/carisma-product-linux.gtk.x86_64.tar.gz /tmp/eclipse.tar.gz	
RUN mkdir /opt/carisma \
    && tar -zxf /tmp/eclipse.tar.gz -C /opt/carisma \
    && rm /tmp/eclipse.tar.gz

# start SSH daemon
CMD ["/usr/sbin/sshd", "-D"]
