<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model2"
    nsURI="http://model2/1.0" nsPrefix="model2">
  <eClassifiers xsi:type="ecore:EClass" name="RuleElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//RuleElementType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongsToSituation" upperBound="-1"
        eType="#//Situation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleElementType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Situation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="has" lowerBound="1" upperBound="-1"
        eType="#//RuleElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Allocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ruleElement" lowerBound="1"
        eType="#//RuleElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bpmnElement" lowerBound="1"
        eType="#//BPMNElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ModelElementType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="incoming" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outgoing" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="processId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleElementAssociationType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//RuleElementType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//RuleElementType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleElementAssociation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="src1" lowerBound="1" eType="#//RuleElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target1" lowerBound="1"
        eType="#//RuleElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type1" lowerBound="1" eType="#//RuleElementAssociationType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsAllocation" upperBound="-1"
        eType="#//Allocation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsSituation" upperBound="-1"
        eType="#//Situation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsBPMNElement" upperBound="-1"
        eType="#//BPMNElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsRuleElementAssociation"
        upperBound="-1" eType="#//RuleElementAssociation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsRuleElement" upperBound="-1"
        eType="#//RuleElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsRuleElemntType"
        upperBound="-1" eType="#//RuleElementType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsRuleElementAssociationType"
        upperBound="-1" eType="#//RuleElementAssociationType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containsModelType" upperBound="-1"
        eType="#//ModelElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatesWith" lowerBound="1"
        upperBound="-1" eType="#//RuleElementType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
