<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="extension4ids" nsURI="http://www.umlsec.de/profiles/UMLsec/extension4ids"
    nsPrefix="extension4ids">
  <eClassifiers xsi:type="ecore:EClass" name="IDSconnector">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="IDS connector"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Artifact" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Artifact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="usagecontrol">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Dependency" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Dependency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="datatransfer">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="data transfer"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transfer_req_step" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Message"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transfer_start_step" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Message"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="push_pull_step" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Message"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transfer_complete_step"
        ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Message"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transfer_suspend_step"
        ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Message"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transfer_terminate_step"
        ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Message"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Interaction" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Interaction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="provider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Lifeline" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Lifeline"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="consumer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Lifeline" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Lifeline"/>
  </eClassifiers>
</ecore:EPackage>
