name: Java CI

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
        
    steps:
    - name: Clone repository with submodules
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0
        submodules: 'recursive'
    - name: Set up JDK version ${{ matrix.Java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.Java }}
        cache: 'maven'  
    - name: Build with Maven and JaCoCo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./mvnw clean verify
